name = "cf-b2b-website"
main = "src/index.js"
compatibility_date = "2025-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "b2b_database"
database_id = "8876731b-609e-4b9f-ad80-12b583d46aea"

# Environment variables
[vars]
ENVIRONMENT = "production"
IMAGEKIT_PUBLIC_KEY = "public_KV5w/2A/gyA7ce8RlTFV+ZdjzTI="
IMAGEKIT_PRIVATE_KEY = "private_iLwYOgaGU7XjQnUkKKzLZx///tc="
IMAGEKIT_URL_ENDPOINT = "https://ik.imagekit.io/ebn7n9wrv"


[[kv_namespaces]]
binding = "STATIC_ASSETS"
id = "ad7742acf23347d995e9bf09e80bb960"