name = "cf-b2b-website"
main = "src/index.js"
compatibility_date = "2025-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "b2b_database"
database_id = "f1d2ceff-31eb-4ed5-a995-24c0c534c0a1"

# Environment variables
[vars]
ENVIRONMENT = "production"
IMAGEKIT_PUBLIC_KEY = "public_KV5w/2A/gyA7ce8RlTFV+ZdjzTI="
IMAGEKIT_PRIVATE_KEY = "private_iLwYOgaGU7XjQnUkKKzLZx///tc="
IMAGEKIT_URL_ENDPOINT = "https://ik.imagekit.io/ebn7n9wrv"


[[kv_namespaces]]
binding = "STATIC_ASSETS"
id = "959962ad6c394a82b222979ac1635bb0"